apiVersion: v1
kind: Service
metadata:
  name: healthcareproject-deployment  
  type: NodePort  
  selector:
    app: healthcareproject-deployment 
  ports:
    - protocol: TCP 
      port: 8082 
      targetPort: 8082 
      nodePort: 30000 
