apiVersion: v1
kind: Service
metadata:
  name: healthcareproject-service
spec:
  selector:
    app: healthcareproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort   # Change from LoadBalancer to NodePort
